language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
script: nosetests
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors unittest2; fi
  - "pip install -r reqs.pip --use-mirrors"
notifications:
  email:
    - semirook@gmail.com